version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: career-crm-backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - FRONTEND_URL=http://localhost:80
      # Database (using SQLite for local deployment)
      - DATABASE_URL=sqlite:///app/data/career_services.db
      # Add other environment variables from .env
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: career-crm-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-data:
  backend-uploads:
  backend-logs: