# fly.toml app configuration file generated for career-services-personal-crm on 2025-08-12T11:53:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'career-services-personal-crm'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
