# Fly.io configuration for Career Services CRM

app = "career-services-crm"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  [build.args]
    NODE_VERSION = "18"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "career_data"
  destination = "/data"
  initial_size = "1gb"

[processes]
  app = "node dist/server.js"