# Fly.io configuration for Career Services CRM
# This uses Buildpacks, NOT Docker - so it won't affect your other Docker projects

app = "career-services-crm"
primary_region = "ams"  # Amsterdam - close to Greece
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  # Using Buildpacks instead of Docker
  builder = "heroku/builder:22"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Persistent storage for SQLite database
[mounts]
  source = "career_data"
  destination = "/data"
  initial_size = "1gb"