# fly.toml app configuration file generated for career-services-personal-crm on 2025-08-12T11:53:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'career-services-personal-crm'
primary_region = 'ams'
kill_signal = "SIGTERM"
kill_timeout = "5s"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "career_data"
  destination = "/app/data"
  initial_size = "1gb"